name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
resources:
- repo: self

trigger:
  batch: true
  branches:
    include:
    - master

jobs:
- template: .azure/devops/pipelines/steps/homepage-build-tooling.yml
- template: .azure/devops/pipelines/steps/homepage-publish.yml
