trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src
pool:
  vmImage: 'ubutnu-latest'
name: $(Build.SourceBranchName).$(Build.BuildId)
steps: 
  - template: .azure/devops/pipelines/steps/homepage-build-tooling.yml
  - template: .azure/devops/pipelines/steps/homepage-publish.yml
