name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src
pool:
  vmImage: 'ubuntu-latest'
steps: 
  - template: .azure/devops/pipelines/steps/homepage-build-tooling.yml
  - template: .azure/devops/pipelines/steps/homepage-publish.yml
