name: SonarCloud-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src
pool:
  vmImage: 'ubuntu-latest'

variables:
  BASH_ENV: "~/.profile"

steps: 
  - template: .azure/devops/steps/sonarcloud.yml