name: Deployment-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger:
  branches:
    include:
    - main
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  BASH_ENV: "~/.profile"

steps: 
  - template: ../steps/homepage-build-tooling.yml
  - template: ../steps/homepage-publish.yml
