name: Deployment-$(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:-r)
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src
pool:
  vmImage: 'ubuntu-latest'

variables:
  BASH_ENV: "~/.profile"

steps: 
  - template: ./.azure/devops/steps/homepage-build-tooling.yml
  - template: ./.azure/devops/steps/homepage-publish.yml
