steps:
- task: SonarCloudPrepare@1
  displayName: 'Prepare analysis on SonarCloud'
  inputs:
    SonarCloud: 'Sonar Cloud  - mikart143'
    organization: mikart143
    scannerMode: CLI
    configMode: manual
    cliProjectKey: 'mikart143_homepage'
    cliProjectName: 'Homepage Frontend'
    cliSources: '$(System.DefaultWorkingDirectory)/src'
- task: SonarCloudAnalyze@1
  displayName: 'Run Code Analysis'
