# This is a basic workflow to help you get started with Actions

name: Deployment

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    defaults:
      run:
        shell: bash
        working-directory: src
    steps:
      - uses: actions/checkout@v3

      - name: Project setup
        uses: volta-cli/action@v1
      
      - name: Dependancy install
        run: npm install
      
      - name: Project build
        run: npm run build
      
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 5db87f304b9e4623fceaf963765ac2b9
          projectName: homepage
          directory: src/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
